#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

//*********************************************************************************
// These settings have been generated for use with TI-RTOS and cc13xxware
//
// Generated by SmartRF Studio version 2.4.3 (build #20)
// Tested for TI-RTOS version tirtos_simplelink_2_21_xx
// Device: CC1310 Rev. 2.1
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_mailbox.h)
#include <ti/drivers/rf/RF.h>


// TI-RTOS RF Mode Object
extern RF_Mode RF_prop_FSK, RF_prop_LRM, RF_prop_SL_LRM, RF_prop_HSM;

// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup_FSK, RF_cmdPropRadioDivSetup_LRM, RF_cmdPropRadioDivSetup_SL_LRM;
extern rfc_CMD_RADIO_SETUP_t RF_cmdRadioSetup_HSM;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx;
extern rfc_CMD_PROP_RX_t RF_cmdPropRx;
extern rfc_CMD_HS_TX_t RF_cmdTxHS;
extern rfc_CMD_HS_RX_t RF_cmdRxHS;

// Legacy Long Range Mode
extern uint32_t pOverrides_625bps[];
// SimpleLink Long Range Mode
extern uint32_t pOverrides_2_5Kbps[];
extern uint32_t pOverrides_5Kbps[];
// FSK
extern uint32_t pOverrides_50Kbps[];
extern uint32_t pOverrides_100Kbps[];
extern uint32_t pOverrides_200Kbps[];
extern uint32_t pOverrides_300Kbps[];
extern uint32_t pOverrides_400Kbps[];
extern uint32_t pOverrides_500Kbps[];
extern uint32_t pOverrides_4Mbps[];

#endif // _SMARTRF_SETTINGS_H_
